"""Comparing two spellings of one person's name.

Speaker names arrive from a parliament's records, from a hand-written registry
entry and from Wikidata, and the three rarely agree on punctuation, accents,
name order, or whether a peerage is part of the name. Deciding when two of
those strings are the same person is a judgement the pipeline has to make in
more than one place, so it is made here once.

`config/speakers/wikidata.yaml` is generated by tools/speakers/enrich_wikidata.py,
which is not part of the distributed tree; the artifact it writes is. Keeping
this comparison in the package rather than in that script is what lets the test
suite check the committed artifact in a checkout that has no tools/ directory.
"""

from __future__ import annotations

import re
import unicodedata

_PUNCT_RE = re.compile(r"[^\w\s]", re.UNICODE)
_WS_RE = re.compile(r"\s+")

# Canonical names for CJK jurisdictions carry the native script in parentheses
# ("Lai Ching-te (賴清德)"), and Wikidata appends a disambiguator to a label it
# needs to keep unique ("Eileen Chong (politician)"). Neither is part of the
# name itself.
PAREN_RE = re.compile(r"\s*[（(][^)）]*[)）]\s*$")


def fold(name: str) -> str:
    """Accent-, case- and punctuation-insensitive key for comparing names.

    'Nilüfer Gündoğan' and 'Nilufer Gundogan' are the same person written by two
    systems with different opinions about diacritics; 'Jean-Michel Arnaud' and
    'Jean Michel Arnaud' likewise. Nothing here changes which characters a name
    *has* -- it only decides whether two spellings count as equal.
    """
    s = unicodedata.normalize("NFKD", name or "")
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = _PUNCT_RE.sub(" ", s.lower())
    return _WS_RE.sub(" ", s).strip()


def same_person(canonical: str, other: str) -> bool:
    """Could these two names belong to the same person?

    Looser than equality on purpose, and used only where identity has already
    been asserted by something other than the name -- a curated Wikidata QID,
    say -- so that the question is not "who is this?" but "is this assertion
    nonsense?". It has to accept the honest disagreements between a registry
    and Wikidata:

      * a peerage the registry carries and the label does not
        ('Martin Rees, Lord Rees of Ludlow' / 'Martin Rees');
      * a Singaporean or Chinese name written surname-first in one and not the
        other ('Kwek Hian Chuan Henry' / 'Henry Kwek');
      * a longer legal name against a shorter public one
        ('Wan Rizal' / 'Wan Rizal Wan Zakariah').

    and reject two names with nothing to do with each other, which is what a
    mistyped QID looks like: 'Thierry Breton' filed against a species of bee,
    'Margrethe Vestager' against a bridge in Berlin. Comparing name tokens as
    sets and accepting containment in either direction does both. One shared
    forename is not containment, so 'Michael McGrath' and 'Michael Detlefsen'
    stay apart.
    """
    a = set(fold(PAREN_RE.sub("", canonical or "")).split())
    b = set(fold(PAREN_RE.sub("", other or "")).split())
    if not a or not b:
        return False
    return a <= b or b <= a
