"""Source ingesters. Each module exposes an `Ingester` subclass registered in REGISTRY."""

from __future__ import annotations


def get_registry():
    """Lazy import so optional deps / missing keys don't break unrelated sources."""
    from . import (
        au_hansard,
        br_senado,
        ca_commons,
        ch_parlament,
        de_bundestag,
        ec_presscorner,
        ep_plenary,
        ep_questions,
        eu_consilium,
        fr_assemblee,
        fr_elysee,
        fr_senat,
        intl_nato,
        intl_un,
        intl_un_webtv,
        jp_kokkai,
        mx_senado,
        nl_officielebekendmakingen,
        nl_tweedekamer,
        ru_duma,
        ru_kremlin,
        sg_parliament,
        tw_ly,
        uk_hansard,
        us_fedreg,
        us_govinfo,
        us_house_hearings,
        us_whitehouse,
        za_pmg,
    )
    from .cn import crawl as cn_crawl

    return {
        "ca_commons": ca_commons.CACommonsIngester,
        "ch_parlament": ch_parlament.CHParlamentIngester,
        "sg_parliament": sg_parliament.SGParliamentIngester,
        "au_hansard": au_hansard.AUHansardIngester,
        "nl_tweedekamer": nl_tweedekamer.NLTweedeKamerIngester,
        "nl_officielebekendmakingen": nl_officielebekendmakingen.NLOfficieleBekendmakingenIngester,
        "tw_ly": tw_ly.TWLYIngester,
        "br_senado": br_senado.BRSenadoIngester,
        "mx_senado": mx_senado.MXSenadoIngester,
        "za_pmg": za_pmg.ZAPMGIngester,
        "ru_kremlin": ru_kremlin.RUKremlinIngester,
        "ru_duma": ru_duma.RUDumaIngester,
        "fr_elysee": fr_elysee.FRElyseeIngester,
        "us_fedreg": us_fedreg.USFedRegIngester,
        "us_whitehouse": us_whitehouse.USWhiteHouseIngester,
        "ep_plenary": ep_plenary.EPPlenaryIngester,
        "ep_questions": ep_questions.EPQuestionsIngester,
        "eu_consilium": eu_consilium.EUConsiliumIngester,
        "ec_presscorner": ec_presscorner.ECPresscornerIngester,
        "intl_nato": intl_nato.NATOIngester,
        "intl_un": intl_un.UNRecordsIngester,
        "intl_un_webtv": intl_un_webtv.UNWebTVIngester,
        "jp_kokkai": jp_kokkai.JPKokkaiIngester,
        "cn_cac": cn_crawl.CNCACIngester,
        "cn_mfa": cn_crawl.CNMFAIngester,
        "cn_gov": cn_crawl.CNGovIngester,
        "cn_most": cn_crawl.CNMOSTIngester,
        "cn_miit": cn_crawl.CNMIITIngester,
        "cn_people": cn_crawl.CNPeopleIngester,
        "de_bundestag": de_bundestag.DEBundestagIngester,
        "fr_assemblee": fr_assemblee.FRAssembleeIngester,
        "fr_senat": fr_senat.FRSenatIngester,
        "uk_hansard": uk_hansard.UKHansardIngester,
        "us_govinfo_crec": us_govinfo.USCRECIngester,
        "us_govinfo_chrg": us_govinfo.USCHRGIngester,
        "us_house_hearings": us_house_hearings.USHouseHearingsIngester,
    }
