"""The corpus figures SCHEMA.md quotes, generated from the payload it describes.

SCHEMA.md is prose about a file, and it had counts sprinkled through that prose:
"688 of ~5,500 rows carry it", "4,267 of 4,267 at the last export", "349 KB of
6.9 MB", "nearly 40% of rows have no `si`". Every one had drifted -- the corpus
was 4,372 rows with 541 `nv` and 3,630 sidecar records, and `si` was absent from
29%, not 40%. Nothing was wrong with the file; the description of it was stale,
which is worse than no number, because a reader checks their parse against it.

So the numbers are generated into one delimited block and the prose points at it.
`tracker export` rewrites the block in both copies of SCHEMA.md, and
`test_schema_counts_block_is_current` fails if it is behind, which makes drift a
test failure instead of a discrepancy nobody is looking for.

Everything here is measured from the published artifacts -- `quotes-data.json` and
the sidecar shards -- rather than from the database, because those are what the
document describes and what a consumer actually receives.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

from .. import config

BEGIN = "<!-- BEGIN generated-counts -->"
END = "<!-- END generated-counts -->"


def _pct(n: int, total: int) -> str:
    return f"{round(100 * n / total)}%" if total else "—"


def measure(site_dir: Path) -> dict:
    payload = json.loads((site_dir / "quotes-data.json").read_text(encoding="utf-8"))
    rows = payload["rows"]
    total = len(rows)
    shards = []
    for i in range(8):
        p = site_dir / f"utterances-{i}.json"
        if p.is_file():
            shards.append(json.loads(p.read_text(encoding="utf-8")))
    records = {k: v for s in shards for k, v in s["u"].items()}
    ids = Counter(r["id"] for r in rows)
    payload_bytes = (site_dir / "quotes-data.json").stat().st_size
    si_bytes = sum(len(r["si"]) for r in rows if "si" in r)
    return {
        "version": payload["v"],
        "rows": total,
        "jurisdictions": len({r["j"] for r in rows}),
        "date_first": min((r["d"] for r in rows), default="—"),
        "date_last": max((r["d"] for r in rows), default="—"),
        "translated": sum(1 for r in rows if "o" in r),
        "nv": sum(1 for r in rows if r.get("nv")),
        "asr": sum(1 for r in rows if r.get("asr")),
        "dp_month": sum(1 for r in rows if r.get("dp")),
        "cu": sum(1 for r in rows if r.get("cu")),
        "si": sum(1 for r in rows if "si" in r),
        "si_absent_pct": _pct(sum(1 for r in rows if "si" not in r), total),
        "si_kb": round(si_bytes / 1024),
        "payload_mb": round(payload_bytes / 1024 / 1024, 1),
        "ul": sum(1 for r in rows if "ul" in r),
        "sidecar_records": len(records),
        "sidecar_with_span": sum(1 for v in records.values() if "s" in v),
        "sidecar_abridged": sum(1 for v in records.values() if v.get("ss")),
        "sidecar_excerpt_pct": _pct(
            sum(1 for v in records.values() if v.get("x")), len(records)
        ),
        "empty_topics": sum(1 for r in rows if not r["t"]),
        "duplicate_ids": sum(1 for n in ids.values() if n > 1),
    }


def render(m: dict) -> str:
    """The block itself. Kept as a table so it reads as reference, not prose."""
    return "\n".join(
        [
            BEGIN,
            "",
            f"*Measured from the {m['version']} payload. Regenerated by `tracker export`;",
            "`test_schema_counts_block_is_current` fails when it drifts. Do not hand-edit.*",
            "",
            "| measure | value |",
            "|---------|-------|",
            f"| rows | {m['rows']:,} |",
            f"| jurisdictions | {m['jurisdictions']} |",
            f"| date range | {m['date_first']} … {m['date_last']} |",
            f"| translated (`o` present) | {m['translated']:,} |",
            f"| not the speaker's words (`nv`) | {m['nv']:,} |",
            f"| machine transcript (`asr`) | {m['asr']:,} |",
            f"| month-precision date (`dp`) | {m['dp_month']:,} |",
            f"| separate citation URL (`cu`) | {m['cu']:,} |",
            f"| portrait (`si`) | {m['si']:,} — absent on {m['si_absent_pct']}, "
            f"costing {m['si_kb']} KB of {m['payload_mb']} MB |",
            f"| surrounding remarks (`ul`) | {m['ul']:,} |",
            f"| sidecar records | {m['sidecar_records']:,}, "
            f"{m['sidecar_with_span']:,} with `s` offsets, {m['sidecar_excerpt_pct']} excerpted |",
            f"| abridged quotes (`ss` segments) | {m['sidecar_abridged']:,} |",
            f"| empty coarse topics (`t`) | {m['empty_topics']:,} |",
            f"| ids shared by more than one row | {m['duplicate_ids']} |",
            "",
            END,
        ]
    )


def schema_paths() -> list[Path]:
    """Both copies of SCHEMA.md -- this repo's and the site's, when present.

    The two must stay identical (see CLAUDE.md), so a generated block has to be
    written to both or the next reader finds them disagreeing about the corpus.
    The site copy is optional, like every other reach across the split.
    """
    return [
        p
        for p in (config.ROOT / "notes" / "SCHEMA.md", config.site_repo() / "SCHEMA.md")
        if p.is_file()
    ]


def write(site_dir: Path) -> list[Path]:
    block = render(measure(site_dir))
    written = []
    for path in schema_paths():
        text = path.read_text(encoding="utf-8")
        if BEGIN not in text or END not in text:
            continue
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        path.write_text(head + block + tail, encoding="utf-8")
        written.append(path)
    return written
